// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: protobufs/path_service.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message
type GetFullPathByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathId uint32 `protobuf:"varint,1,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
}

func (x *GetFullPathByIDRequest) Reset() {
	*x = GetFullPathByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_path_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFullPathByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullPathByIDRequest) ProtoMessage() {}

func (x *GetFullPathByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_path_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullPathByIDRequest.ProtoReflect.Descriptor instead.
func (*GetFullPathByIDRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_path_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetFullPathByIDRequest) GetPathId() uint32 {
	if x != nil {
		return x.PathId
	}
	return 0
}

// Response message
type GetFullPathByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    *PathResponse `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFullPathByIDResponse) Reset() {
	*x = GetFullPathByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_path_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFullPathByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullPathByIDResponse) ProtoMessage() {}

func (x *GetFullPathByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_path_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullPathByIDResponse.ProtoReflect.Descriptor instead.
func (*GetFullPathByIDResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_path_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetFullPathByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFullPathByIDResponse) GetData() *PathResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// Path response message
type PathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DistanceKm       float64 `protobuf:"fixed64,2,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	Code             string  `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name             string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type             string  `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	FromCountry      string  `protobuf:"bytes,6,opt,name=from_country,json=fromCountry,proto3" json:"from_country,omitempty"`
	FromCity         string  `protobuf:"bytes,7,opt,name=from_city,json=fromCity,proto3" json:"from_city,omitempty"`
	FromTerminalName string  `protobuf:"bytes,8,opt,name=from_terminal_name,json=fromTerminalName,proto3" json:"from_terminal_name,omitempty"`
	ToCountry        string  `protobuf:"bytes,9,opt,name=to_country,json=toCountry,proto3" json:"to_country,omitempty"`
	ToCity           string  `protobuf:"bytes,10,opt,name=to_city,json=toCity,proto3" json:"to_city,omitempty"`
	ToTerminalName   string  `protobuf:"bytes,11,opt,name=to_terminal_name,json=toTerminalName,proto3" json:"to_terminal_name,omitempty"`
}

func (x *PathResponse) Reset() {
	*x = PathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_path_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathResponse) ProtoMessage() {}

func (x *PathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_path_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathResponse.ProtoReflect.Descriptor instead.
func (*PathResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_path_service_proto_rawDescGZIP(), []int{2}
}

func (x *PathResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PathResponse) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *PathResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PathResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PathResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PathResponse) GetFromCountry() string {
	if x != nil {
		return x.FromCountry
	}
	return ""
}

func (x *PathResponse) GetFromCity() string {
	if x != nil {
		return x.FromCity
	}
	return ""
}

func (x *PathResponse) GetFromTerminalName() string {
	if x != nil {
		return x.FromTerminalName
	}
	return ""
}

func (x *PathResponse) GetToCountry() string {
	if x != nil {
		return x.ToCountry
	}
	return ""
}

func (x *PathResponse) GetToCity() string {
	if x != nil {
		return x.ToCity
	}
	return ""
}

func (x *PathResponse) GetToTerminalName() string {
	if x != nil {
		return x.ToTerminalName
	}
	return ""
}

var File_protobufs_path_service_proto protoreflect.FileDescriptor

var file_protobufs_path_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x70, 0x61, 0x74, 0x68,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13,
	0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x70, 0x61, 0x74, 0x68, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x31, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x50, 0x61,
	0x74, 0x68, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x70, 0x61, 0x74, 0x68, 0x49, 0x64, 0x22, 0x6a, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c,
	0x6c, 0x50, 0x61, 0x74, 0x68, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x70, 0x61, 0x74, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0xcb, 0x02, 0x0a, 0x0c, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x6b, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x4b, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x69, 0x74, 0x79,
	0x12, 0x2c, 0x0a, 0x12, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x72,
	0x6f, 0x6d, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x6f, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x6f, 0x43, 0x69, 0x74, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x6f, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x74, 0x6f, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x32, 0x7b, 0x0a, 0x0b, 0x50, 0x61, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x42, 0x79,
	0x49, 0x44, 0x12, 0x2b, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x70, 0x61, 0x74,
	0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c,
	0x50, 0x61, 0x74, 0x68, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x70, 0x61, 0x74, 0x68, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x50, 0x61, 0x74,
	0x68, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x22, 0x5a,
	0x20, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_path_service_proto_rawDescOnce sync.Once
	file_protobufs_path_service_proto_rawDescData = file_protobufs_path_service_proto_rawDesc
)

func file_protobufs_path_service_proto_rawDescGZIP() []byte {
	file_protobufs_path_service_proto_rawDescOnce.Do(func() {
		file_protobufs_path_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_path_service_proto_rawDescData)
	})
	return file_protobufs_path_service_proto_rawDescData
}

var file_protobufs_path_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobufs_path_service_proto_goTypes = []any{
	(*GetFullPathByIDRequest)(nil),  // 0: terminalpathservice.GetFullPathByIDRequest
	(*GetFullPathByIDResponse)(nil), // 1: terminalpathservice.GetFullPathByIDResponse
	(*PathResponse)(nil),            // 2: terminalpathservice.PathResponse
}
var file_protobufs_path_service_proto_depIdxs = []int32{
	2, // 0: terminalpathservice.GetFullPathByIDResponse.data:type_name -> terminalpathservice.PathResponse
	0, // 1: terminalpathservice.PathService.GetFullPathByID:input_type -> terminalpathservice.GetFullPathByIDRequest
	1, // 2: terminalpathservice.PathService.GetFullPathByID:output_type -> terminalpathservice.GetFullPathByIDResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobufs_path_service_proto_init() }
func file_protobufs_path_service_proto_init() {
	if File_protobufs_path_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_path_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetFullPathByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_path_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetFullPathByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_path_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_path_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_path_service_proto_goTypes,
		DependencyIndexes: file_protobufs_path_service_proto_depIdxs,
		MessageInfos:      file_protobufs_path_service_proto_msgTypes,
	}.Build()
	File_protobufs_path_service_proto = out.File
	file_protobufs_path_service_proto_rawDesc = nil
	file_protobufs_path_service_proto_goTypes = nil
	file_protobufs_path_service_proto_depIdxs = nil
}
