global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

providers:
  consulCatalog:
    endpoint:
      address: "consul:8500"

log:
  level: "DEBUG"
  filePath: "logs/traefik.log"

accessLog:
  filePath: "logs/access.log"

#tracing:
#  serviceName: traefik
#  otlp:
#    http:
#      endpoint: "http://otel-collector:55680/v1/traces"
#  jaeger:
#    collector:
#      endpoint: "http://otel-collector:55680/v1/traces"
