// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: protobufs/path_service.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PathService_GetFullPathByID_FullMethodName = "/pathservice.PathService/GetFullPathByID"
)

// PathServiceClient is the client API for PathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PathServiceClient interface {
	GetFullPathByID(ctx context.Context, in *GetFullPathByIDRequest, opts ...grpc.CallOption) (*GetFullPathByIDResponse, error)
}

type pathServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPathServiceClient(cc grpc.ClientConnInterface) PathServiceClient {
	return &pathServiceClient{cc}
}

func (c *pathServiceClient) GetFullPathByID(ctx context.Context, in *GetFullPathByIDRequest, opts ...grpc.CallOption) (*GetFullPathByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFullPathByIDResponse)
	err := c.cc.Invoke(ctx, PathService_GetFullPathByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathServiceServer is the server API for PathService service.
// All implementations must embed UnimplementedPathServiceServer
// for forward compatibility.
type PathServiceServer interface {
	GetFullPathByID(context.Context, *GetFullPathByIDRequest) (*GetFullPathByIDResponse, error)
	mustEmbedUnimplementedPathServiceServer()
}

// UnimplementedPathServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPathServiceServer struct{}

func (UnimplementedPathServiceServer) GetFullPathByID(context.Context, *GetFullPathByIDRequest) (*GetFullPathByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullPathByID not implemented")
}
func (UnimplementedPathServiceServer) mustEmbedUnimplementedPathServiceServer() {}
func (UnimplementedPathServiceServer) testEmbeddedByValue()                     {}

// UnsafePathServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PathServiceServer will
// result in compilation errors.
type UnsafePathServiceServer interface {
	mustEmbedUnimplementedPathServiceServer()
}

func RegisterPathServiceServer(s grpc.ServiceRegistrar, srv PathServiceServer) {
	// If the following call pancis, it indicates UnimplementedPathServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PathService_ServiceDesc, srv)
}

func _PathService_GetFullPathByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFullPathByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathServiceServer).GetFullPathByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathService_GetFullPathByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathServiceServer).GetFullPathByID(ctx, req.(*GetFullPathByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PathService_ServiceDesc is the grpc.ServiceDesc for PathService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PathService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pathservice.PathService",
	HandlerType: (*PathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullPathByID",
			Handler:    _PathService_GetFullPathByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobufs/path_service.proto",
}
